mixed-port: 2080
allow-lan: false
tcp-concurrent: true
enable-process: true
find-process-mode: strict
global-client-fingerprint: chrome
mode: rule
log-level: warning
ipv6: true
tcp-keep-alive: true  # 🔥 Включаем Keep-Alive для стабильности соединения
keep-alive-interval: 15
unified-delay: true

profile:
  store-selected: true
  store-fake-ip: false
  store-ruleset: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  stack: mixed
  mtu: 1500
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  listen: 0.0.0.0:5353
  enhanced-mode: redir-host
  ipv6: true
  cache: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://dns.vancrafter.click/dns-query
  fallback:
    - https://family.cloudflare-dns.com/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query
  proxy-server-nameserver:
    - https://dns.quad9.net/dns-query
    - https://security.cloudflare-dns.com/dns-query


rule-providers:
  
  refilter_domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./re-filter/domain-rule.mrs
    interval: 86400
    
  refilter_ipsum:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/ip-rule.mrs
    path: ./re-filter/ip-rule.mrs
    interval: 86400

  oisd_big:
    type: http 
    behavior: domain 
    format: mrs 
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/oisd/big.mrs
    path: ./oisd/big.mrs
    interval: 86400

  oisd_nsfw_big:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/oisd/nsfw.mrs
    path: ./oisd/nsfw_big.mrs
    interval: 86400

  ads_all:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads-all.yaml
    path: ./meta/ads_all.yaml
    interval: 86400

  ads_lite:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ads.yaml
    path: ./meta/ads_lite.yaml
    interval: 86400

  win_spy:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/win-spy.yaml
    path: ./meta/win_spy.yaml
    interval: 86400   
    
  porn:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-porn.yaml
    path: ./meta/porn.yaml
    interval: 86400
    
  youtube:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/youtube.yaml
    path: ./meta/youtube.yaml
    interval: 86400

  facebook:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/facebook.yaml
    path: ./meta/facebook.yaml
    interval: 86400
  

  google:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/google.yaml
    path: ./meta/google.yaml
    interval: 86400
    
  microsoft:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/microsoft.yaml
    path: ./meta/microsoft.yaml
    interval: 86400

  openai:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/openai.yaml
    path: ./meta/openai.yaml
    interval: 86400  

  tiktok:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geosite/tiktok.yaml
    path: ./meta/tiktok.yaml
    interval: 86400  

  trello:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/trello.yaml
    path: ./meta/trello.yaml
    interval: 86400   

  perplexity:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/perplexity.yaml
    path: ./meta/perplexity.yaml
    interval: 86400     

  google-gemini:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google-gemini.yaml
    path: ./meta/google-gemini.yaml
    interval: 86400      
    
  no-russia-hosts:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/ru-bundle/no-russia-hosts.mrs
    path: ./ru-bundle/no-russia-hosts.mrs
    interval: 86400


rules:

  # Торренты - отправляем напрямую (Windows + Android)
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,utorrent.exe,DIRECT
  - PROCESS-NAME,bittorrent.exe,DIRECT
  - PROCESS-NAME,deluge.exe,DIRECT
  - PROCESS-NAME,bitcomet.exe,DIRECT
  - PROCESS-NAME,vuze.exe,DIRECT
  - PROCESS-NAME,tixati.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,frostwire.exe,DIRECT
  - PROCESS-NAME,com.utorrent.client,DIRECT
  - PROCESS-NAME,com.bittorrent.client,DIRECT
  - PROCESS-NAME,com.delphicoder.flud,DIRECT
  - PROCESS-NAME,org.proninyaroslav.libretorrent,DIRECT
  - PROCESS-NAME,hu.tagsoft.ttorrent.pro,DIRECT
  - PROCESS-NAME,com.mobilityflow.torrent,DIRECT
  - PROCESS-NAME,com.intelligems.torrdroid,DIRECT
  - PROCESS-NAME,com.frostwire.android,DIRECT
  - PROCESS-NAME,com.vuze.android.remote,DIRECT
  - PROCESS-NAME,com.biglybt.android.client,DIRECT
  - PROCESS-NAME,player.torrserve,DIRECT  # TorrServe Matrix

  # Торрент-порты - напрямую
  - DST-PORT,6881-6889,DIRECT
  - DST-PORT,51413,DIRECT
  - DST-PORT,12345,DIRECT

  - DOMAIN,pornolab.net,Auto Select
  - RULE-SET,porn,REJECT 
  - RULE-SET,ads_all,REJECT 
  - RULE-SET,ads_lite,REJECT 
  - RULE-SET,win_spy,REJECT
  - RULE-SET,oisd_big,REJECT
  - RULE-SET,oisd_nsfw_big,REJECT
 # - DOMAIN,rezka.ag,Rezka
  - RULE-SET,google-gemini,Gemini
  - RULE-SET,google,Auto Select
  - RULE-SET,trello,Auto Select
  - RULE-SET,perplexity,Auto Select
  - RULE-SET,openai,Auto Select
  - RULE-SET,tiktok,Auto Select
  - RULE-SET,youtube,Auto Select
  - RULE-SET,facebook,Auto Select
  - RULE-SET,microsoft,Auto Select
  - RULE-SET,refilter_domains,Auto Select
  - RULE-SET,refilter_ipsum,Auto Select
  - RULE-SET,no-russia-hosts,Auto Select

  # Остальное — напрямую
  - MATCH,DIRECT
    
