name: Build and Commit Geosite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Download geosite binary
      run: |
        wget https://github.com/v2fly/geosite/releases/download/v0.0.1/geosite_linux_amd64
        chmod +x geosite_linux_amd64
        mkdir -p $HOME/go/bin
        mv geosite_linux_amd64 $HOME/go/bin/geosite
        echo "$HOME/go/bin" >> $GITHUB_PATH
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Run conversion script
      run: python geosite_converter.py

    - name: Commit and push geosite.dat
      run: |
        # Настройка git
        git config --global user.name "RichardMoor75"
        git config --global user.email "rishat.murtazin@gmail.com"

        # Проверка изменений
        if git diff --exit-code --quiet geosite.dat; then
          echo "No changes to geosite.dat"
          exit 0
        fi

        # Коммит и пуш
        git add geosite.dat
        git commit -m "Auto-update geosite.dat"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
