name: Fetch and Convert AdGuard to SRS & MRS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0" # Каждое воскресенье в 8:00 утра по UTC

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and install Mihomo and sing-box
        run: |
          mkdir -p tmp/convert
          # sing-box
          wget -O sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.25/sing-box-1.10.0-alpha.25-linux-amd64.tar.gz
          tar zxvf sing-box.tar.gz && rm sing-box.tar.gz
          cp sing-box-1.10.0-alpha.25-linux-amd64/sing-box tmp/convert/
          chmod +x tmp/convert/sing-box
          rm -r sing-box-1.10.0-alpha.25-linux-amd64
          # Mihomo (Clash.Meta)
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases \
            | grep "browser_download_url.*mihomo-linux-amd64-alpha.*\.deb" \
            | head -n 1 \
            | cut -d '"' -f 4 \
            | xargs wget -q -O mihomo-linux-amd64-alpha.deb
          sudo apt install --fix-missing ./mihomo-linux-amd64-alpha.deb

      - name: Fetch AdGuard DNS Filter Lists
        run: |
          wget -O tmp/convert/AdGuardDNSFilter.txt https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt
          if [ ! -f tmp/convert/AdGuardDNSFilter.txt ]; then
            echo "Failed to download AdGuardDNSFilter.txt"
            exit 1
          fi

      - name: Convert filters to SRS and MRS using sing-box and Mihomo
        run: |
          cd tmp/convert
          for file in *.txt; do
            echo "Converting $file to .srs with sing-box..."
            ./sing-box rule-set convert "$file" --output "${file%.txt}.srs" --type adguard || { echo "Conversion to .srs failed"; exit 1; }

            echo "payload:" > temp.yaml
            sed "s/.*/- '+.&'/" "$file" >> temp.yaml

            echo "Converting $file to .mrs with Mihomo..."
            mihomo convert-ruleset domain yaml temp.yaml "${file%.txt}.mrs" || { echo "Conversion to .mrs failed"; exit 1; }
            rm temp.yaml
          done
          cd ../..
          rm -rf binary/adguard && mkdir -p binary/adguard
          cp tmp/convert/*.srs tmp/convert/*.mrs binary/adguard/
          rm -rf tmp && ls -l binary/adguard

      - name: Configure Git
        run: |
          git config --global user.name "RichardMoor75"
          git config --global user.email "rishat.murtazin@gmail.com"

      - name: Check for Changes and Commit
        run: |
          git add binary/adguard
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            echo "changes=false" >> $GITHUB_ENV
          else
            git commit -m "actions: Update AdGuard filters (srs & mrs)"
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Push Changes
        if: env.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
