name: Merge and Upload Geosite Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Install sing-box
      run: |
        LATEST_URL=$(curl -sL https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep "browser_download_url" | grep "linux-amd64.tar.gz" | cut -d '"' -f 4)
        wget $LATEST_URL -O sing-box.tar.gz
        tar -xzf sing-box.tar.gz
        mv sing-box-*-linux-amd64 sing-box
        chmod +x sing-box

    - name: Download original geosite.dat
      run: curl -L -o original_geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Download custom geosite.dat
      run: curl -L -o custom_geosite.dat https://github.com/1andrevich/antifilter-domain/releases/latest/download/geosite.dat

    - name: Decode both geosite files
      run: |
        mkdir -p decoded/original decoded/custom
        ./sing-box geo export-geosite --input original_geosite.dat --output decoded/original
        ./sing-box geo export-geosite --input custom_geosite.dat --output decoded/custom

    - name: Merge decoded folders
      run: |
        cp -r decoded/custom/* decoded/original/

    - name: Encode merged geosite.dat
      run: |
        ./sing-box geo compile-geosite --input decoded/original --output config/binary/geosite/geosite.dat

    - name: Check if there are changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add config/binary/geosite/geosite.dat
        git diff --cached --exit-code || echo "Changes detected"

    - name: Commit and push changes if any
      if: success() || failure()
      run: |
        git diff --cached --quiet || (git commit -m "Update merged geosite.dat" && git push)
