name: Merge and Upload Geosite Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Install geo-tool
      run: |
        wget https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64.zip
        unzip mihomo-linux-amd64.zip
        chmod +x geo-tool

    - name: Download original geosite.dat
      run: curl -L -o original_geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Download custom geosite.dat
      run: curl -L -o custom_geosite.dat https://github.com/1andrevich/antifilter-domain/releases/latest/download/geosite.dat

    - name: Decode both geosite files
      run: |
        mkdir decoded/original decoded/custom
        ./geo-tool decode --format domainlist original_geosite.dat decoded/original
        ./geo-tool decode --format domainlist custom_geosite.dat decoded/custom

    - name: Merge decoded folders
      run: |
        cp -r decoded/custom/* decoded/original/

    - name: Encode merged geosite.dat
      run: |
        ./geo-tool encode --format domainlist decoded/original config/binary/geosite/geosite.dat

    - name: Check if there are changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add config/binary/geosite/geosite.dat
        git diff --cached --exit-code || echo "Changes detected"

    - name: Commit and push changes if any
      if: success() || failure()
      run: |
        git diff --cached --quiet || (git commit -m "Update merged geosite.dat" && git push)
