name: Merge and Upload Geosite Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build geoip-tool
      run: |
        git clone https://github.com/MetaCubeX/geoip.git
        cd geoip/tool
        go build -o ../../geoip-tool
        cd ../../

    - name: Download original geosite.dat
      run: curl -L -o original_geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Download custom geosite.dat
      run: curl -L -o custom_geosite.dat https://github.com/1andrevich/antifilter-domain/releases/latest/download/geosite.dat

    - name: Decode both geosite files
      run: |
        mkdir -p decoded/original decoded/custom
        ./geoip-tool decode -i original_geosite.dat -o decoded/original
        ./geoip-tool decode -i custom_geosite.dat -o decoded/custom

    - name: Merge decoded folders
      run: |
        cp -r decoded/custom/* decoded/original/

    - name: Encode merged geosite.dat
      run: |
        ./geoip-tool encode -i decoded/original -o config/binary/geosite/geosite.dat

    - name: Check if there are changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add config/binary/geosite/geosite.dat
        git diff --cached --exit-code || echo "Changes detected"

    - name: Commit and push changes if any
      if: success() || failure()
      run: |
        git diff --cached --quiet || (git commit -m "Update merged geosite.dat" && git push)
