name: Merge and Upload Geosite Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Install Python and Protobuf
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler
        pip install protobuf
        protoc --python_out=. geosite.proto

    - name: Download original geosite.dat
      run: curl -L -o original_geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Download custom geosite.dat
      run: curl -L -o custom_geosite.dat https://github.com/1andrevich/antifilter-domain/releases/latest/download/geosite.dat

    - name: Create target folder
      run: mkdir -p config/binary/geosite

    - name: Merge geosite files
      run: |
        python merge_geosite.py

    - name: Check if there are changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add config/binary/geosite/geosite.dat
        git diff --cached --exit-code || echo "Changes detected"

    - name: Commit and push changes if any
      if: success() || failure()
      run: |
        git diff --cached --quiet || (git commit -m "Update merged geosite.dat" && git push)
